### PR TITLE
Event filtering

### LINKED ISSUE #15: Event Paginate
- After singing in the user will be redirected to a view where he can see all events that he has registered
  - When signed in the user will be redirected to a page where he can see his registered events, but not other user's events unless they're public
  -  [x] Title, location, and date must be mandatory fields
  -  [x] User should be redirected to a page where he can see his registered events
  -  [x] User should not be able to see other user's events
  -  [x] User can only see other user's events if they're marked as public in another view
  
- Event list should be paginated
  - [x] Events are displayed on the page by 'x' number of events each

### PR DESCRIPTION
**Pull request by hugocruz1234**
In this pull request, we associate the event model with the user model, in order to have a better control of the events created by the users. In addition to implementing a validation, so that an event can only be modified or deleted by the user who created it. 

Also with the help of the "will_paginate" gem, a pagination was applied to the table where the events are shown.

For more details #15 

image

image

image

image

image

image

### CODE REVIEW

**Comment by Antonio3veces3** [comment]
Excelent!

**Review by Antonio3veces3 — APPROVED** [review]
Excelent!

**Review by BrandonVG — APPROVED** [review]
LGBTQ+

**Comment by Ballo1988** [comment]
Thanks guys!

**Pull request merged**
